name: Morphological CI/CD

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  validate-evolve:
    name: Validate and Evolve Instances
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup jq and Python
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Validate repository structure
        run: |
          chmod +x scripts/validate_repo.sh
          ./scripts/validate_repo.sh repo.json

      - name: Simulate evolution
        run: |
          chmod +x scripts/evolve_instances.sh
          ./scripts/evolve_instances.sh repo.json 3

      - name: Git snapshot
        run: |
          chmod +x scripts/git_snapshot.sh
          ./scripts/git_snapshot.sh

      - name: Python bridge
        run: |
          chmod +x scripts/python_bridge.sh
          ./scripts/python_bridge.sh repo.json

      - name: Orchestration script
        run: |
          chmod +x scripts/git.sh
          ./scripts/git.sh repo.json
